### ISSUE TITLE
Find a more robust way to inject header 

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/web-extension#1]
![image](https://cloud.githubusercontent.com/assets/89555/21057046/302fbb06-be1f-11e6-9396-548b6c629c4e.png)

is not the first condition in which happen, I'll document these in this issue

**Comment by vrde** [comment]
I noticed this as well. The problem goes away when you scroll, right?

**Comment by vecna** [comment]
I don't remember that, but I'm even thinking we can keep track all the times the banner get injected, and every time the validate API is called, we communicate such number. might be part of a statistic linked to the supporterId, to understand:

  * is for some reason coming back ?
  * are many the user using different browsers (have we to explain it more?)
  * how many times the user have to see it before publish the banner ?

I don't know if, for example, some user don't want publicize the project openly (and therefore we shall support a different onboarding process)

**Comment by vecna** [comment]
cool the new one! #5
