### ISSUE TITLE
Restore the popup link, store in localstorage the auth token

### ISSUE THREAD

**Issue by vrde** [tracking-exposed/web-extension#100]
# Problem
To access the personal page, the user does not use the publicKey, but rather, an authentication token.

I add this because the publicKey can't revoke if it gets lost, but the token can be refreshed and let only the legitimate owner access the page.

The API `/api/v1/selector`, contacted when the extension run, received this auth token. 

It means the user can't access to the personal page without having before retrieved this auth token, and at the moment, this happens only when the facebook.com tab is open. 

I suggest to save it in localStorage after the first retrieval, and assume, soon or later, the `/api/v1/selector` might return a new access token, and this should override the previous.

**Comment by vrde** [comment]
Blocked by https://github.com/tracking-exposed/facebook/pull/148

**Comment by vecna** [comment]
https://facebook.tracking.exposed/reality-check/#TOKENTOKEN234565434567
