### ISSUE TITLE
Advanced settings editing mode from the popup

### ISSUE THREAD

**Issue by vrde** [tracking-exposed/web-extension#102]
# Problem

In certain conditions, the researcher asks to collect content different from the newsfeed. apparently, would be enough a checkbox, let's say the researcher open the special panel, and click on "specialOccasion = true"

```
function evaluateIfCollectionShouldBeDone() {
    return (window.location.href == '/' || config.specialOccasion );
}
```

But should not be so simple because collecting data outside of the newsfeed is a violation of our privacy statement and this data should be treat differently in the backend.

in regards of the privacy statement, a research using this data should collect this copy only for them. In the backend processing, this data should not be part of our semantic analysis, nor in content statistics (except, perhaps, in the "amount of content excluded from the pipeline"). because would not be about the facebook algorithm, but a content needed for a specific research, which only benefit of our passive scraping feature.

# Solution

1. a `<smaller>` link to 'advanced settings'
2. which open a pop-up section
3. with the checkbox 'specialOccasion' (to be renamed) 
4. if the 'specialOccasion' check clicked, a warning message appears
5. in the timeline, a new Boolean field should be add, on the logic of evaluating `window.location.href`, so server side this data can be marked properly and excluded from processing.

I suggest this sequence because the point 3 above, in the future, might contain others checkboxes/options.

**Comment by vecna** [comment]
how can i recognize server side the different package? via location matching?

**Comment by vrde** [comment]
Do you mean the two custom headers `X-Fbtrex-Version` and `X-Fbtrex-Build`?
