### ISSUE TITLE
Improve UX in group (tagId/groupId) joining process 

### ISSUE THREAD

**Issue by vrde** [tracking-exposed/web-extension#103]
# Problem

_Describe the problem here_

**Comment by vecna** [comment]
After some consideration, I believe the best approach is to let the tagging happen backend side.

* this is experimental on youtube.tracking.exposed at the moment
* reduce complexity to the web-extension 
* anyway, should in the backend where we've to allow update/delete/revision of tagged content

the current popup used for tagging, might be transformed in the one defined on #102

**Comment by vrde** [comment]
Should this ticket be closed in favor of #102?

**Comment by vrde** [comment]
After talking to @vecna we can safely close this issue.
