### ISSUE TITLE
Remove fbtrex button in the bottom left corner

### ISSUE THREAD

**Issue by vrde** [tracking-exposed/web-extension#15]
# Beginners welcome!
This issue is easy to handle, and we can guide you through its resolution! Read the *description* and the *how to solve it* sections.

If you are **not** a beginner, take a look to [other issues](https://github.com/tracking-exposed/web-extension/issues), thanks!

# Description
From https://github.com/tracking-exposed/web-extension/pull/7#issuecomment-267948909, by @vecna:
> [...] if the interaction with fb.tr.ex can pass through that banner [@vrde says: And the popup menu], can we remove the logo? doesn't the page looking "monopolized" by the project, being so recurrent?

Since #11, the button has become redundant and it can be removed.

![image](https://cloud.githubusercontent.com/assets/134680/21318130/43b565f4-c608-11e6-8241-45055e430f96.png)

# How to solve it
- [ ] fork this repository
- [ ] clone it on your machine
- [ ] do what's in the [Getting Started](https://github.com/tracking-exposed/web-extension#getting-started) document to set up your working environment
- [ ] go to [facebook.com](https://www.facebook.com/), you should see a big banner asking you to post your public key to a public post. Ignore this for now.
- [ ] take a look to the `render` function in [`src/app.js`](https://github.com/tracking-exposed/web-extension/blob/v1.0.4/src/app.js) file. This is where the button is rendered.
- [ ] the main button is rendered **after** the onboarding. To make the onboarding work you need the API server running in localhost as well. What you can do is add a call to the `render` function in [`app.js:59`](https://github.com/tracking-exposed/web-extension/blob/v1.0.4/src/app.js#L59) to display the button, to trigger a rendering even if you didn't do the onboarding
- [ ] try to remove the line that renders the button
- [ ] reload your browser, the button should be gone
- [ ] remove all the code related to the button. Don't forget the styles!
- [ ] create a PR and submit it
- [ ] party! :tada: :balloon: :dancer:

**Comment by vecna** [comment]
you would like use this issue to engage new devs?

**Comment by vrde** [comment]
> you would like use this issue to engage new devs?

yep :smile: https://twitter.com/vrde/status/810882916771393536

**Comment by shivasheeshyadav** [comment]
@vrde I would like to work on this issue.

**Comment by vrde** [comment]
@shivasheeshyadav it has already been fixed, see #17.

(I just noticed that closing the issue via the PR didn't work because the description says "fix for #15" and not "fix #15").
