### ISSUE TITLE
As a user, when an infobox is displayed on a post in the newsfeed, I want to be able to dismiss it.

### ISSUE THREAD

**Issue by vrde** [tracking-exposed/web-extension#16]
From https://github.com/tracking-exposed/web-extension/pull/7#issuecomment-267948909, by @vecna:
> the size: seems to big? will became annoying? will make feel users uncomfortable? the best improvement for me might be:
a way to close such banner permanently, communicated server side, and only if the user exert some advanced option in the page, we communicate back to the extension to display it again. This has sense if the banner is only informative.

![image](https://cloud.githubusercontent.com/assets/134680/21318647/54b08be8-c60a-11e6-802e-469b0059a9c0.png)

The idea is to:
- add a **dismiss** action
- when **dismiss** is clicked, a flag is stored in `chrome.storage.local`, and a message is sent to the server

Note that this requires also a **settings** panel for the extension. A natural place can be the `popup.html` window.

**Comment by vecna** [comment]
tested, working
