### ISSUE TITLE
As a user taking part in a study group, I want to specify a tag to my data so it can be used for research purposes

### ISSUE THREAD

**Issue by vrde** [tracking-exposed/web-extension#21]
Some users might take part in a study group. The data of those users should be easy to query. The idea is to add a box in the extension pop up so users can self tag themselves.

The tag will be then added to the payload sent to the API.

@vecna there are a couple of ways to achieve that:
1. add a `tag` field to each event the extension send to the API
2. add `tag` in the headers, e.g. `x-fbtrex-tag`

Do you have other ideas? Probably the first solution is the better.

**Comment by vecna** [comment]
it is OK the first

I wonder if is better save such information in the localstorage (only) or in the server (first) and communicate that to the client(s).
In case is the second, in the personal page, user might specify their user tag(s)

**Comment by vecna** [comment]
tested, working
