### ISSUE TITLE
Possible private posts being shared as Public.

### ISSUE THREAD

**Issue by konarkmodi** [tracking-exposed/web-extension#59]
I found few cases, which looked private to me, may be I am still trying to understand the definition of private vs public.

But these are usually posts in which my friends have been tagged in a photo or uploaded a photo, or did a live facebook session.

<img width="511" alt="screen shot 2017-08-24 at 22 37 19" src="https://user-images.githubusercontent.com/440520/29687824-10317522-891e-11e7-8fbb-13770fa4f6bc.png">
<img width="500" alt="screen shot 2017-08-24 at 22 40 14" src="https://user-images.githubusercontent.com/440520/29687873-284c1d2e-891e-11e7-9e31-1a9f57887a52.png">

**Comment by vecna** [comment]
but that is the appropriate behavior: both of the post have the "world" icon, so they are shared publicly

**Comment by vecna** [comment]
the world icon is the one Facebook uses to identify when a post could be seen by everyone (even non-Facebook users), we are liking the original Facebook explanation here: https://facebook.tracking.exposed/privacy-statement 

If you see some non-world-icon being recorded: that's a serious bug, but at the moment, the detection works with a logic like: "we are sure or we didn't record". Re-open the issue if you see that behavior, thanks!
