### ISSUE TITLE
npm test fails !

### ISSUE THREAD

**Issue by konarkmodi** [tracking-exposed/web-extension#60]
Running `npm test` after cloning the repo and `npm install`, gives the following error.
<img width="714" alt="screen shot 2017-08-27 at 00 37 21" src="https://user-images.githubusercontent.com/440520/29745621-30eff83a-8ac0-11e7-894d-1cd70250c1b7.png">

**Comment by vecna** [comment]
I don't know exactly why was happening. also, the way to do test, relay in having some HTML saved used as test for the extension, we should update that approach using some recently retrieved HTML.
