### ISSUE TITLE
Default locale was specified, but _locales subtree is missing.

### ISSUE THREAD

**Issue by konarkmodi** [tracking-exposed/web-extension#61]
After building the extension with `npm run build`, when loading the extension in chrome, gives the following error : 
<img width="392" alt="screen shot 2017-08-27 at 00 41 29" src="https://user-images.githubusercontent.com/440520/29745637-a2ee5a94-8ac0-11e7-819a-45a1af3b857d.png">

I could make it work after copying the `_locales` folder inside the `build` folder. Looks like a webpack issue.

**Comment by vecna** [comment]
thank you, the copy is only implemented here: https://github.com/tracking-exposed/web-extension/commit/cd1ecc23c7b5701a11b52df112a28c9c6b8ac16b as you suggest has to be moved in webpack script

**Comment by vecna** [comment]
this was solved since some time, it should work in all the condition now.
