### ISSUE TITLE
Disable the green color on facebook bar

### ISSUE THREAD

**Issue by Mte90** [tracking-exposed/web-extension#63]
It is possible to set the original color bar on Facebook?

**Comment by vecna** [comment]
No, it is not. At the moment, at least, it is on purpose green (to remind to the supporters, they have the extension installed)

We can add such switch in the control box. If the issue remains open, we will deal with this problem as asked.

but exactly, why?

**Comment by Mte90** [comment]
Because on Facebook everything is blue and everytime I don't recognize the site for green bar also if it is facebook.
Usually to recognize that there is an extension an icon is enough (there is the bar Your data for that)

**Comment by Mte90** [comment]
The bar is blue again <3

**Comment by vecna** [comment]
Even better, now has shades ;) I've to keep something, another idea is to substitute the facebook logo with fbtrex
