### ISSUE TITLE
(chrome browser) http 500 error from promoted posts csv

### ISSUE THREAD

**Issue by lucacorsato** [tracking-exposed/web-extension#66]
the API's url for promoted posts from cvs give "error http 500" [error](https://facebook.tracking.exposed/api/v1/personal/csv/100012524134185/promoted)

**Comment by vecna** [comment]
Thanks, sorry for the delay.

**Comment by vecna** [comment]
Bug  confirmed, has to be managed, but it is happening only in users without any kind of promoted posts

**Comment by vecna** [comment]
This bug was due to the logic in the backend API, it costed a major restructuring of the interaction between webapp and APIs. Large files can't be served as content, it is better if we create an incremental archive to be downloaded as files.
