### ISSUE TITLE
(Chrome Browser) Facebook.tracking.exposed unable to complete onboarding

### ISSUE THREAD

**Issue by MissPeace** [tracking-exposed/web-extension#68]
I just added F.T.E. to my Chrome Browser, I followed the instructions putting the message as a public post and then deleting it after more than a minute but the boarding still results not completed.
Any solutions?

**Comment by vecna** [comment]
Thanks @MissPeace, I confirm, the onboarding is not working in these days. Facebook changed something and I didn't catch up in time. But I'm taking some time to make the onboarding an optional procedure (and figure out a more reliable way to do it)

**Comment by vecna** [comment]
Solved, with the new version 1.1.12, the onboarding is just not anymore display. It has to comeback with more option soon.
