### ISSUE TITLE
After month of use seems that nothing is tracked by the extension

### ISSUE THREAD

**Issue by Mte90** [tracking-exposed/web-extension#69]
![screenshot_20171219_221221](https://user-images.githubusercontent.com/403283/34179111-f0629968-e509-11e7-99f6-accfc8fcc8d0.png)

I installed the extension was released also for Firefox but this is what I get when i am trying to see my data.
I censured my id but inspecting mthe request result empty (contain only `[]`).

There is something that I can do to help on that? I am actually using Firefox Nightly with PrivacyBadger and Tracking protection enabled.

**Comment by vecna** [comment]
Thanks for the feedback, I've to say:
  * the collection it is working, we are using it daily to run experiments and the open stats show a constant income of HTMLs
  * sometime I see error from mongodb. It is a problem in the `personal` section, like the one you are querying, and basically it the one occurring to you. I know how to fix it, it is getting triggered more often lately.

update soon, 🤞

**Comment by Mte90** [comment]
Ok because also the other sections was empty so I was wondering if in my case is logging or not.

**Comment by vecna** [comment]
Just a couple of questions:
  * did you see the banner on top of your post? (post recorded?)
  * can you try to change the second number of days, putting something more than 5 ? for example, it is working to me even going back of 60 days: `https://facebook.tracking.exposed/api/v1/htmls/100022366722172/days/60`

The same API, will return 0 elements by default, because that user is a bot not used since some weeks, and the default behavior is like yours:

![image](https://user-images.githubusercontent.com/89555/34216083-8e549412-e5a7-11e7-87b5-9716733ee1b4.png)

**Comment by Mte90** [comment]
Nope, the url is https://facebook.tracking.exposed/api/v1/htmls/1312682052/days/60 and as you can see is empty.
About the recording I have the label `This post will be kept private` on my posts.

**Comment by vecna** [comment]
all the posts "private" means they are not recorded (they are never sent to the server)... now, that's the point to investigate into.. can you look into the console of facebook.com, and see if the messages from the extension contain any insights?

second: probably the message has to be more explicit, saying *this post is not collected* ?

**Comment by Mte90** [comment]
![screenshot_20171220_171830](https://user-images.githubusercontent.com/403283/34216867-e4d6d474-e5a9-11e7-84de-5fb29339198b.png)
This is what I am getting on all the posts on facebook, so I was guessing that is tracking them but only me can see that kind of data.
The extension doesn't have a settings panel so I was thinking that that behaviour was normal.
![screenshot_20171220_172116](https://user-images.githubusercontent.com/403283/34216979-4d69b768-e5aa-11e7-9884-62c5edf98998.png)
It is not easy to reconize the errors of the extension, maybe write in a different color?

**Comment by vecna** [comment]
Debugging your user contributions:
`
> db.timelines2.count({userId: 1312682052})
2598
`
Seeing your first and last timeline collected:
`
> db.timelines2.find({userId: 1312682052})[0]
{
        "_id" : ObjectId("59c031c34c32ba4c7710b8a4"),
        "startTime" : ISODate("2017-09-18T20:50:53Z"),
        "userId" : 1312682052,
        "geoip" : "IT",
        "id" : "0aa6c2eb2b001afb35119f77ae54d7d72519b544"
}
> db.timelines2.find({userId: 1312682052})[2597]
{
        "_id" : ObjectId("5a3a8189cf09256bcb92f61b"),
        "startTime" : ISODate("2017-12-20T15:28:03Z"),
        "userId" : 1312682052,
        "geoip" : "IT",
        "id" : "3194dc403302cba974c5f3cd79813d5dbef91619"
}
> db.htmls2.count({userId: 1312682052})
0
> db.impressions2.count({userId: 1312682052})
23967
> db.impressions2.find({userId: 1312682052})[12345]
{
        "_id" : ObjectId("5a05b2ce4fef4a660df7bf60"),
        "visibility" : "private",
        "timelineId" : "cd89df96bf46457a9f6d9a46a8583d2e85d326a6",
        "id" : "90076264dfd2d846f7ba58622d37a4ef83c0e061",
        "userId" : 1312682052,
        "impressionOrder" : 26,
        "impressionTime" : ISODate("2017-11-10T14:08:02Z")
}
`
Also, I saw you are using 1.1.11 as version.. didn't firefox trigger an auto update to the 1.1.12?

**Comment by Mte90** [comment]
Seems no, but I trigger and updated right now.
I get that alert about private also on public stuff not only for friends.

So if it is collecting why on the website api say that is empty?

**Comment by vecna** [comment]
It is not collecting the HTML, and the website API returns metadata extracted from the HTML, like this:
![image](https://user-images.githubusercontent.com/89555/34217656-5355bcec-e5ac-11e7-9b8e-d9ff7c3ff0fc.png)

The problem I'm seeing is the error message *unable to scrape post* in your console log: all the post not scraped, are considered private. A question: which language is your Facebook GUI?

**Comment by Mte90** [comment]
Uuh the language of my Facebook is Esperanto but is not yet fully localized in that language so is a mix with english.

**Comment by vecna** [comment]
That's could be the problem, sadly at the moment, the few (nearly reliabe) hook we have to use in Facebook content, are language dependent:
https://github.com/tracking-exposed/web-extension/blob/master/src/scrape.js#L10

question for you: what's the word you see when you go "onmouseover" the world symbol on Facebook? I need that work in the list.

second: I was trying to do a mathematical analysis, when all the post looks private, try to raise an alarm to the backend. But that part is not ready yet. It could help to spot any language changes (or any new user with an unsupported language)

**Comment by Mte90** [comment]
The word is `publika` :-)

**Comment by vecna** [comment]
boom, I'll issue a new version, thanks and sorry for the inconvenience. Probably in the 2018 a method like /api/v1/selector will we implemented with these word (making the update only an effort server side)

Considering this experience, what can be improve in our side about communicating to the user what's going on?

**Comment by Mte90** [comment]
I think improving the experience is important.
SO if I switch to english the language I will see my post tracked on the website?

**Comment by vecna** [comment]
Yes, indeed, if you switch to any of the supported language it should work.

**Comment by Mte90** [comment]
Switched on Italian and the posts are recorded but the website is still empty.

**Comment by vecna** [comment]
check now ;) it takes between 1 minute and 2 to run all the parsers 
```
> db.htmls2.count({userId: 1312682052})
6
```

**Comment by Mte90** [comment]
Yes now is working!

**Comment by vecna** [comment]
I closed the issue but it is actually a good suggestion and something I would have done before, but I've not really the skill for this. anyway, now this is on the next milestone.

**Comment by vecna** [comment]
finally we have it 
![image](https://user-images.githubusercontent.com/89555/50730696-cb2a1000-1153-11e9-92bd-4560ec814ecd.png)
