### ISSUE TITLE
resolve the google chrome takedown

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/web-extension#72]
![image](https://user-images.githubusercontent.com/89555/39827281-d001d734-53b7-11e8-9c8b-963e22fb33e3.png)

since more than two months we're in take down for trademark infringement. Despite I open contact with the complainer, nothing is changed.

Also OpenRightsGroup wrote about this issue https://www.openrightsgroup.org/blog/2018/facebook-don’t-want-you-to-know-how-their-algorithm-works but nothing is changed so far.

**Comment by vecna** [comment]
Mentioned here for https://github.com/mozilla/global-sprint/issue/308

**Comment by vecna** [comment]
published 1.1.13, waiting: 
![image](https://user-images.githubusercontent.com/89555/39860224-d1fed674-543c-11e8-8bf9-eac2bb08b8e3.png)

**Comment by vecna** [comment]
Nope, has been rejected without any justification from Google, now I've apply again
![image](https://user-images.githubusercontent.com/89555/39868865-badc84b8-545b-11e8-969c-c14bef2b65da.png)

**Comment by vecna** [comment]
The commit with the diffs is here https://github.com/tracking-exposed/web-extension/commit/61a707e42ea70924f39c7d25fd5ef23a54f8d4d1

**Comment by vecna** [comment]
Nope, we are still taken down without any explanation 
![image](https://user-images.githubusercontent.com/89555/39921777-73e2dae6-551c-11e8-86e0-f876ba6fe9bb.png)

**Comment by vrde** [comment]
:skull: :skull: :skull:

**Comment by vecna** [comment]
![image](https://user-images.githubusercontent.com/89555/42884067-a37e887a-8a9d-11e8-9958-293fb8ceaf3c.png)

nothing

**Comment by vecna** [comment]
Also with a different `item` uploaded, seems something has marked _FbTREX_ extension:
![image](https://user-images.githubusercontent.com/89555/42889856-ac700dba-8aab-11e8-881b-8f80bb80eb4b.png)

**Comment by vecna** [comment]
now has been published a new `item` with version 1.1.16, this is not taken down, but still means we can't update the previous users and the reasons of the takedown are not yet truly solved.

**Comment by vecna** [comment]
this has been resolved, for now. it took months for legal mismanagement
