### ISSUE TITLE
package.json scripts don't work on Windows env

### ISSUE THREAD

**Issue by FloweryScythe13** [tracking-exposed/web-extension#74]
This may be due to the fact that my machine is Windows 7, as I had noticed that the build:watch:files script in package.json relies on the command cp (not copy as is required on Windows). 

After editing the above in package.json to use copy, I get the following output from npm run start. The files manifest.json, popup.html, and everything under the _locales/ and icons/ directories are present. 

```

> tracking-exposed-extension@1.1.14 build:watch:files C:\Users\brichem\Security-
Practice-Projects\web-extension
> rimraf ./build && mkdir build && copy -r manifest.json icons/* _locales/ popup
.html ./build/ && cross-env webpack -w

The system cannot find the file specified.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tracking-exposed-extension@1.1.14 build:watch:files: `rimraf ./build &&
 mkdir build && copy -r manifest.json icons/* _locales/ popup.html ./build/ && c
ross-env webpack -w`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tracking-exposed-extension@1.1.14 build:watch:files script.


```

**Comment by vecna** [comment]
Thanks, you right. but are you sure the copy on windows with "./" can work?

**Comment by vecna** [comment]
I renamed the issue, but I never experienced it also because I'm using conemu
![image](https://user-images.githubusercontent.com/89555/40052728-fcda9562-583e-11e8-8065-bbb206cbb1c6.png)
https://en.wikipedia.org/wiki/ConEmu

**Comment by vecna** [comment]
I'm observing `npm run start` doesn't perform as it doing on Linux, but I'm also using more often `npm run build` and then pointing the temporary extension to `build/manifest.json`

**Comment by vecna** [comment]
Any feedback? can I close the issue? (has been released a new version, in which the `git` dependency cease to be mandatory)

**Comment by vecna** [comment]
# WHATEVER
