### ISSUE TITLE
The web extension seems to not work properly on firefox 63

### ISSUE THREAD

**Issue by fisiognomico** [tracking-exposed/web-extension#80]
Hi everyone! I have compiled locally the web-extension, with the backend set to localhost.

I have checked the developer console, and it seems that is set correctly, the problem is that the mongo db is not populated and in general the web extensions is not capable of communicating with localhost.

I use firefox 63 developer-ed. The bug is not reproduced with Chromium 69.

As a side note, after the application is build and I start the backend, in Firefox the FB-bar becomes green but I window which asks if I accept to send my metadata su fbtrex does not appear, and also the green check when a post in the timeline is collected is not present. Maybe the error resides here, as the web extension is not capable of obtaining the permissions to harvest user data.

**Comment by vecna** [comment]
Hi, recently a new version has been issued. Can you test it now? thanks

**Comment by DokFaust** [comment]
It seems to not work yet. The error when I load the manifest in firefox is 
`Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.`
Also

**Comment by vecna** [comment]
Hi, sorry but to me is working well with firefox 64, can you tell me more about the bug?
