### ISSUE TITLE
add Extension ID to manifest.json

### ISSUE THREAD

**Issue by berli0z** [tracking-exposed/web-extension#88]
adding extension id in this format: 
`{
    "manifest_version": 2,
    "applications": {
        "gecko": {
            "id": "firefox@tampermonkey.net",
            "strict_min_version": "48.0"
        }
    }`
would allow to deploy a bundled firefox with preinstalled extensions

**Comment by vecna** [comment]
I'll check which exactly _id_ should be used, but I doubt would be an email @tampermoney.net ;)

**Comment by vecna** [comment]
I realized someone else had the same need: https://github.com/0rC0/web-extension/commit/bc563f52513bcbfb2ebfa4ad89e71b77f5c09bb1 @0rC0

**Comment by 0rC0** [comment]
In my case the id let me pack an xpi with an unsigned developer version of the extension and install it in Firefox Developer Edition (so neither with Mozilla Store and their Signature nor with the Process described in the README). 

The idea was to make a "base" Firefox profile with the extension preinstalled to be used with some Selenium automatized sessions.

I can say it installs but everything ist still WIP for now.

**Comment by vecna** [comment]
But you are suggesting different formats, would be better if you mention the reference document next time ( https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings )

**Comment by vecna** [comment]
please check if with the last commit it fits your purpose
