### ISSUE TITLE
Architecture and dependencies are outdated

### ISSUE THREAD

**Issue by vrde** [tracking-exposed/web-extension#95]
# Problem
Architecture and dependencies are outdated. This leads to:
- Security issues.
- Technical debt.

# Solution
There are two different solutions possible:

- Update dependencies and continue with the previous architecture. Pros: faster to implement. Cons: future development will slow down.
- Refactoring using newer tools. Pros: easier to integrate new functions, easier to have a single web extension to support multiple projects. Cons: slower, more risky.

# Deliverable
An updated web extension that works exactly as before, but better, more maintainable, more secure.

**Comment by vecna** [comment]
Considering this extension has been the underlying codebase copied to implement the collection for Youtube, Pornhub, and Amazon, and considering I would update these extensions accordingly to the new design, I prefer the second option. I want to keep each .tracking.exposed project potentially open to external and aperiodic contributions; I need to spin off experiments without minding too much maintenance and to have newer tools should also help in this regard.

**Comment by vrde** [comment]
Yeah, this is also what I thought. It will require more work on my side, but it should also allow me to speed up the development of some of the new issues, and will make future development faster and more pleasurable.
