### ISSUE TITLE
Suspend extension activity

### ISSUE THREAD

**Issue by vrde** [tracking-exposed/web-extension#97]
# Problem

Once the user opts in for participating to the project, there is no way they can suspend or pause the extension from scraping the feed. This might lead to uninstalls, or in general frustration for the end user

# Solution

Allow users to suspend the activity of the extension. Ideally this should be reflected also on the icon, as users should know when the activity is paused.

# Deliverable

A button in the popup to suspend the scraper activity.

**Comment by vecna** [comment]
I confirm, also, to be considered part of #96, if a person postpone the on-boarding initial opt-in, this should be equivalent of having the extension suspended.
