### ISSUE TITLE
Test how the extension behave when "Facebook Container" is active

### ISSUE THREAD

**Issue by vrde** [tracking-exposed/web-extension#99]
# Problem

Firefox [Facebook Container](https://addons.mozilla.org/en-US/firefox/addon/facebook-container/) is an extension that:

> Prevent Facebook from tracking you around the web. The Facebook Container extension for Firefox helps you take control and isolate your web activity from Facebook.

We currently don't know how this extension behaves when Facebook Container is active.

# Solution

Try to understand what's happening here.

# Deliverable

Implement strategies to work better when Facebook Container is active. Will refine this issue on a next iteration.

**Comment by vecna** [comment]
The underlay technology is the "firefox containers" https://support.mozilla.org/en-US/kb/containers?as=u&utm_source=inproduct this means the API accessing to the cookie should consider this condition before accessing to the shared cookie jar.

**Comment by vrde** [comment]
I've done some research :microscope: 

[Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) works!

[Facebook Container](https://addons.mozilla.org/en-US/firefox/addon/facebook-container/) on the other side is quite strict:

- It doesn't allow the extension (background) to retrieve the user's cookie.
- It doesn't allow the background page or pop-up page to communicate with content script, the error is "Error: Could not establish connection. Receiving end does not exist.".

**Comment by vecna** [comment]
I'll test this today https://github.com/tracking-exposed/facebook.tracking.exposed/issues/22

**Comment by vecna** [comment]
note, the current work in progress has is triggering unclear dynamics 

![image](https://user-images.githubusercontent.com/89555/74854955-4d699980-5340-11ea-9257-b1f6d2049ae9.png)
